services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movieexplorer-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: movieexplorer-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  movieexplorer-api:
    build:
      context: ./MovieExplorer.API
      dockerfile: Dockerfile

    container_name: movieexplorer-api

    depends_on:
      - sqlserver
      - redis

    ports:
      - "7176:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=${MSSQL_DB};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False"

      Redis__ConnectionString: redis:6379

    restart: unless-stopped

  movieexplorer-ui:
    build:
      context: ./movie-explorer-ui
      dockerfile: Dockerfile

    container_name: movieexplorer-ui

    depends_on:
      - movieexplorer-api

    ports:
      - "3000:80"

    restart: unless-stopped

volumes:
  sqlserver_data: